cessda/cessda.cdc.searchkit

- server/helper.ts
- src/containers/DetailPage.tsx
- tests/common/mockdata.ts
- tests/server/helper.ts
- tests/src/actions/detail.ts
Google Dataset Search, as specified at https://developers.google.com/search/docs/appearance/structured-data/dataset, requires the "description" field to be at least 50 characters long. This PR limits the generation of embedded JSON-LD metadata to studies with abstracts longer than 50 characters.
The JSON-LD representation can still be directly requested using API calls.
This closes cessda/cessda.cdc.versions#544.
> #544: Only create embedded JSON-LD representations when the abstract is longer than 50 characters

- server/views/index.ejs
- src/components/Detail.tsx
- src/components/Result.tsx
- src/components/Similars.tsx
- src/containers/DetailPage.tsx
- tests/src/components/Detail.tsx
- tests/src/components/Similars.tsx
All metadata fields on Detail page have lang attribute except for PID, data collection period, publication year and related publications. Related publications should have lang for each publication but that would require knowing their language and that is a bit out of scope for this issue.
Lang attributes for translations added only for the three that actually have a translation in every language.
> #543: Add lang attribute to top level html element and metadata on front page and detail page

- src/components/Detail.tsx
- src/components/Similars.tsx
- src/containers/SearchPage.tsx
- src/styles/modules/_body.scss
- tests/src/containers/SearchPage.tsx
- translations/en.json
Mostly happy with how keywords filter works here but still not sure about the way I used searchkit's RefinementListFilter's showMore with increased facetsPerPage to make it possible to easily search from all keywords. Having all keywords listed and searchable makes the dropdown slightly slow to open on my PC/browser/dev server at least but I still think it's good to have that option. It would also look better with the texts being "Search from all keywords" and "Search from 2000 most common keywords" but it's more ambiguous (could think it needs to be pressed to initiate the search).
Might still be better to just decide on a number of keywords to show/search from and disable showMore for keywords also. It would still work when clicking a keyword in Detail view even if the keyword is …
> #561: Change keywords filter to be similar to topic filter, update Topic filter tooltip text, fix key in Similars

- server/views/index.ejs
- src/styles/design.scss
- src/styles/modules/_feedback.scss
Form styles rely on class names used in https://eosc-helpdesk.eosc-portal.eu/assets/form/form.js but I'd assume it's safe to do so and they won't suddenly be changed/removed without warning (some deprecation warnings are in the script but not for these).
Leaving out autocomplete attributes from this ([WCAG 2.1 SC 1.3.5](https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html)), e.g. autocomplete="name". This is something that would generally require changes to the previously mentioned script (either directly add attributes there or add support for custom attributes).
> Add styles for feedback button and form, remove placeholder texts from feedback form

- server/helper.ts
- server/metrics.ts
This fixes an invalid simple_query_string query being sent to Elasticsearch, fixing broken Postman tests.
> Only add a keywords query if keywords are being sent to the API

- src/components/Header.tsx
- src/components/Pagination.tsx
- src/components/Panel.tsx
- src/components/Reset.tsx
- src/components/Result.tsx
- src/components/Tooltip.tsx
- src/containers/AboutPage.tsx
- src/containers/DetailPage.tsx
- src/containers/NotFoundPage.tsx
- src/containers/SearchPage.tsx
- src/styles/modules/_body.scss
- src/styles/modules/_header.scss
- src/styles/modules/_tooltip.scss
- tests/src/components/Header.tsx
- tests/src/components/Panel.tsx
- tests/src/components/Result.tsx
- translations/en.json
Fixes almost all issues with keyboard navigation. Still can't tab to selected filter values in side panel or filter summary window but everything is still technically usable with just keyboard because all the filters can easily be cleared with "Reset filters".
Outline color for visible focus is the same light orange that is used in some places on main CESSDA website since it looked better than just black outline.
"Skip to main content" link is vertically centered with quite oldschool CSS trick but using Bulma's is-vcentered on the parent with columns class would require changing CSS for all the elements in header (above bluestripe).
> #562: Improve keyboard navigation, focus order and visible focus, add skip to main

- CHANGELOG.md
- server/elasticsearch.ts
- server/helper.ts
- server/metrics.ts
- tests/server/helper.ts
This PR separates all Elasticsearch communications used when gathering metrics and moves them to `elasticsearch.ts`. The initialisation of the metrics was moved to the function that returns the request handler, ensuring that the correct metrics will always be initialised.
Other changes:
- Fix type errors with Elasticsearch aggreagtions.
- Fix incorrect results when gathering the amount of records per language
- Fix incorrect results when gathering the amount of records per endpoint
- Only query IP address location when a valid IPInfo API key is provided
- Fix response time tracking milliseconds instead of seconds.
- Removed redundant metrics
- `api_response_time_duration_seconds_total`
- `api_response_time_duration_seconds_total_success`
- `api_response_time_duration_seconds_user_failed` …
> Fix various bugs related to Prometheus metrics, remove redundant metrics

- src/containers/SearchPage.tsx
Requires the index changes from https://github.com/cessda/cessda.cdc.osmh-indexer.cmm/pull/41 to work.
> #609: Use normalized field for Topic and Keywords filters

- src/components/Panel.tsx
- tests/src/components/Header.tsx
- tests/src/components/Panel.tsx
- tests/src/components/Result.tsx
- tests/src/components/Tooltip.tsx
Checks that target element isn't in content part of Panel before toggling collapsed so no need to exclude them separately. I'm pretty sure just excluding 'input' would have also worked in the current state but better to not have to worry that I missed something else.
Also added some calls of mockRestore in tests that I realized I hadn't added previously when using jest.spyOn.
> #610: Fix Panel to not toggle collapsed when target of keyboard event is in content

- README.md
- server/elsst.ts
Went with your solution so I didn't use ```localname``` since it's optional while ```uri``` is required.
Works fine with how ELSST currently is but I was wondering if it would be a good idea to also have additional check for the value of ```resultUri.replace(ELSST_URI_PREFIX, '')``` so that it actually only contains uuid (like if length is 36).
Also ended up just writing final url as ```${SKOSMOS_URL}/${ELSST_VOCABULARY}/en/page/${resultUriUuid}?clang=${lang}``` since at least currently it can mostly be constructed from already existing env variables but maybe it would be useful to have something like ```const ELSST_URL = process.env.SEARCHKIT_ELSST_URL || `${SKOSMOS_URL}/${ELSST_VOCABULARY}/en/page`;```.
> #617: Modify ELSST link if it contains known prefix to add clang parameter

- common/metadata.ts
- src/components/Detail.tsx
- src/components/Keywords.tsx
- src/components/Result.tsx
- src/containers/App.ts
- src/utilities/elsst.ts
- tests/common/metadata.ts
- tests/common/mockdata.ts
- tests/src/components/Keywords.tsx
- tests/src/components/Result.tsx
- tests/src/containers/App.tsx
- translations/en.json
These results list changes required some other changes for everything to work correctly.
- App can update <code>key</code> of children (<code>SearchPage</code>) to update page even if location didn't change
- <code>AbortController</code> for ELSST term fetching in <code>Keywords</code> in case user navigates while fetch is still going
- <code>Keywords</code> always requires <code>keywordLimit</code> parameter to keep the code simple
> #415: Changes to results list: shorten abstract and add randomly chosen keywords below

- src/components/Detail.tsx
- src/components/Keywords.tsx
- src/utilities/elsst.ts
- tests/src/components/Keywords.tsx
Using a `ref` is unnecessary, simply having a plain `AbortController` that lasts the lifetime of the components mount is clearer. This also avoids having to use the null-forgiveness operator `!`.
> Simplify the handling of the AbortController in the Keywords component

- package-lock.json
- package.json
- server/elasticsearch.ts
- server/elsst.ts
- server/helper.ts
- server/views/index.ejs
- src/actions/language.ts
- src/components/Header.tsx
- src/components/Pagination.tsx
- src/components/Panel.tsx
- src/components/Result.tsx
- src/components/SearchBox.ts
- src/containers/SearchPage.tsx
- src/reducers/search.ts
- src/utilities/language.ts
- src/utilities/searchkit.ts
- tests/server/elasticsearch.ts
- tests/server/helper.ts
- tests/src/components/Detail.tsx
- tests/src/components/Header.tsx
- tests/src/components/SearchBox.tsx
- tests/src/components/Similars.tsx
- tests/src/containers/DetailPage.tsx
- tests/src/reducers/search.ts
- webpack.common.ts
This makes the code easier to read and removes unnecessary dependencies that have known transitive dependency security issues.
> Remove the "bodybuilder" NPM dependency and construct Elasticsearch requests directly

- common/metadata.ts
- src/components/Detail.tsx
- tests/src/components/Detail.tsx
Grant number not mandatory in indexer anymore (https://github.com/cessda/cessda.cdc.osmh-indexer.cmm/pull/120).
> #560: Grant number optional for funding information

- common/metadata.ts
- src/components/Detail.tsx
- tests/common/metadata.ts
- tests/common/mockdata.ts
- tests/src/components/Detail.tsx
- translations/en.json
Requires indexing with [https://github.com/cessda/cessda.cdc.osmh-indexer.cmm/pull/122](https://github.com/cessda/cessda.cdc.osmh-indexer.cmm/pull/122) to work.
SPs using Data Kind in DDI-C 2.5 mostly use values that basically the same as in [DDI-L 3.3 General Data Format CV](https://vocabularies.cessda.eu/vocabulary/GeneralDataFormat)  so I think it makes sense to combine them under Kind of Data. [DDI-C 2.5 dataKind element](https://ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/field_level_documentation_files/schemas/codebook_xsd/elements/dataKind.html) has an example ```<dataKind type="numeric">survey data</dataKind>``` so I'm not sure where the values Quantitative, Qualitative and Mixed that FSD are using should be but we have them as the text value while in [DDI-L 3.3 …
> #567: Update data model to include Data Kind and General Data Format, display them combined as Kind of Data on Display page

- src/components/Detail.tsx
- src/components/OrcidLogo.tsx
- src/styles/modules/_body.scss
- tests/src/components/Detail.tsx
Not perfectly happy about having to use `transform: translateY(-2px);` to vertically align the logo (`vertical-align: middle;` alone is not perfect). It could be done with `align-items: center;` with flexbox but I tried it and it just becomes too much of a mess to then get everything else perfect.
I replaced "ORCID: " with this ORCID logo since it basically conveys the same information.
> #677: Add ORCID iD icon before ORCID iD URL

- server/helper.ts
- src/components/Topbar.tsx
- src/containers/SearchPage.tsx
- tests/src/components/SortingSelector.tsx
Requires mappings changes to indices from https://github.com/cessda/cessda.cdc.osmh-indexer.cmm/pull/157.
Could have been fixed by changing the search query in <code>helper.ts</code> to search from nested paths but I feel like it's better and simpler by adding search fields in mappings that can be used instead.
> #685: Fix searching from creators and keywords, rename fields with normalizer from raw to normalized

- src/App.tsx
Fixes https://github.com/cessda/cessda.cdc.versions/issues/721. It wasn't related to the recently created <code>CustomRefinementList</code>. Instead I've just forgot to add it to stateMapping in routing when first adding data access support and it has gone unnoticed since then.
> #721: Fix selected data access filter options missing from query params

- common/metadata.ts
- server/elasticsearch.ts
- src/components/Detail.tsx
- tests/common/mockdata.ts
- tests/src/components/Detail.tsx
Added sort for related publications and also link for related publications is now the first one that starts with <code>http</code> instead of just the first holdings value since not all URIs are URLs.
Requires building indices again with https://github.com/cessda/cessda.cdc.osmh-indexer.cmm/pull/189 to work.
> #660: Sort related publications by publication date, check that publication link starts with http

- server/elsst.ts
See https://github.com/cessda/cessda.cdc.searchkit/security/code-scanning/4
> Fix ELSST URL sanitisation by replacing `includes()` with `startsWith()`

- common/metadata.ts
- src/components/Result.tsx
- tests/common/metadata.ts
- tests/src/components/Result.tsx
This PR replaces the `sanitizeAnchorTags()` function with a DOM equivalent. This will catch all instances of `<a>` tags.
The regex that matches highlight words does not handle regex special characters. This PR adds the ability for such characters to be escaped before attempting to construct the regex.
See https://github.com/cessda/cessda.cdc.searchkit/security/code-scanning/5
> Use DOM APIs to sanitise <a> tags, escape all special regex characters when highlighting
